helix-bridge/wormhole-ui

vercel.json

same with: https://github.com/darwinia-network/home/pull/172

vercel security headers

---

.maintain/vercel/deploy.sh

When push code to `master` `staging` will build use `yarn build` command other branch use `yarn build:dev`

Vercel deploy

---

src/components/bridge/Darwinia2Ethereum.tsx
src/components/controls/AssetGroup.tsx

fix(#38): d2e ring amount validation

---

src/components/controls/AssetGroup.tsx

fix(#43): ring amount validation

---

public/locales/en/translation.json
public/locales/zh/translation.json
src/components/Airport.tsx

fix(#49): validation msg

---

src/components/records/Records.tsx

fix(#63): disable tron records

---

src/App.tsx

feat: add docs extra links

---

CHANGELOG.md
package.json

chore: add changelog

---

src/components/bridge/Darwinia2Ethereum.tsx

fix(#88): ss58 prefixed account

---

public/locales/en/translation.json
public/locales/zh/translation.json
src/App.tsx

fix(#86): update beta tip msg

---

public/index.html

fix(#82): update website meta

---

src/components/Footer.tsx

fix(#83): remove term of use

---

src/components/controls/AssetGroup.tsx

fix(#90): update ring validation

---

src/App.tsx
tailwind.config.js

fix(#100): nav color

---

package.json
src/index.tsx
yarn.lock

fix(#85): loading

---

src/components/bridge/Darwinia2Ethereum.tsx

fix(#87): requery balance when account changed

---

src/components/records/Records.tsx

high CPU usage in records query

chore: high cpu usage

---

.gitignore
src/components/modal/TransferConfirm.tsx
src/components/modal/TransferSuccess.tsx
src/utils/records/d2e.ts

fix(#108): prefixed polkadot address

---

.gitignore
public/locales/en/translation.json
public/locales/zh/translation.json
src/components/modal/ApproveSuccess.tsx
src/components/modal/TransferSuccess.tsx

fix(#106): subscan link text

---

src/utils/records/d2e.ts

chore: mmr args

---

public/locales/en/translation.json
public/locales/zh/translation.json
src/components/bridge/DVM.tsx
src/components/bridge/Darwinia2Ethereum.tsx
src/components/bridge/Substrate2SubstrateDVM.tsx
src/components/controls/PolkadotAccountsItem.tsx
src/components/records/AssetOverview.tsx
src/components/records/ProgressDetail.tsx
src/components/records/Records.tsx
src/components/records/S2SRecord.tsx
src/config/query.ts

alert confirmed fail status
fix #133

s2s record patch

---

src/components/bridge/Darwinia2Ethereum.tsx

fix(#142): d2e balance

---

public/index.html
public/less.min.js

chore: remove less cdn

---

src/components/records/ProgressDetail.tsx
src/components/records/Records.tsx
src/hooks/s2sRecords.tsx
src/utils/tx/redeem.ts

hack response

---

package.json
src/components/BallScalePulse.tsx
src/index.tsx
tailwind.config.js

fix(#103): fall back loading, etc

---

src/components/records/D2ERecord.tsx

fix(#173): token name

---

src/config/network.ts

Fix the problem that the fee is too high when transferring from Darwinia to Ethereum.

fix: switch darwinia rpc

---

src/components/bridge/Darwinia2Ethereum.tsx

fix(#184): d2e transfer with only kton

---

src/components/bridge/Darwinia2Ethereum.tsx

fix(#184): d2e transfer with only kton (#185)

---

.github/workflows/test-e2e.yml
.github/workflows/test-unit.yml
src/__tests__/Balance.test.tsx

test: add test case for balance component

---

package.json
src/components/bridge/Darwinia2Ethereum.tsx
yarn.lock

fix(#194): d2e fee

---

.github/ISSUE_TEMPLATE/1-bug-report.yaml
.github/PULL_REQUEST_TEMPLATE.md
cypress/integration/ethereum2Darwinia.spec.ts
src/components/SubmitButton.tsx
src/components/bridge/Darwinia2Ethereum.tsx
src/components/bridge/Ethereum2Darwinia.tsx
src/components/controls/AssetGroup.tsx
src/model/network.ts
src/providers/api-provider.tsx
src/utils/helper/balance.ts
src/utils/helper/block.ts
src/utils/helper/validate.ts
src/utils/network/connection.tsx
src/utils/network/network.ts
src/utils/tx/redeem.ts

fix some known connection issue
promblems that may be occurred during Polkadot API reconnecting

refactor: polkadot connection

---

src/__tests__/Destinantion.test.tsx
src/components/controls/RecipientItem.tsx
src/config/network.ts
src/model/network.ts
src/utils/network/network.ts

chore: remove fullName field from network config

---

src/components/records/D2ERecord.tsx
src/utils/records/issuing.ts

fix(#199): connection check before claim

---

cypress.json
cypress/integration/ethereum2Darwinia.spec.ts
cypress/integration/substrateDVM2Substrate.spec.ts
public/locales/en/translation.json
public/locales/zh/translation.json
src/components/records/D2ERecord.tsx
src/config/abi/S2SMappingToken.json
src/config/network.ts
src/utils/helper/balance.ts
src/utils/mmr/proof.ts
src/utils/network/network.ts

fix(#23): add daily limit check

---

package.json
src/components/records/Record.tsx
src/components/records/S2SRecord.tsx
src/config/constant.ts
src/config/query.ts
src/utils/erc20/token.ts
src/utils/network/network.ts
yarn.lock

substrate -> substrate DVM: record time UTC to local
temporary fix

fix: record time

---

src/__tests__/Progress.test.tsx
src/__tests__/Record.test.tsx
src/components/records/Record.tsx
src/config/network.ts
src/config/query.ts
src/hooks/records.tsx
src/model/darwinia/dapp.ts

refactor: switch subql endpoints

---

public/locales/en/translation.json
public/locales/zh/translation.json
src/components/bridge/SubstrateDVM2Substrate.tsx
src/utils/helper/validate.ts
src/utils/network/connection.tsx
src/utils/network/entrance.ts

chore: remove manual reconnect

---

package.json
public/locales/en/translation.json
public/locales/zh/translation.json
src/components/Configuration.tsx
src/components/bridge/DVM.tsx
src/components/bridge/Substrate2SubstrateDVM.tsx
src/components/bridge/SubstrateDVM2Substrate.tsx
src/components/finder.tsx
src/components/records/Record.tsx
src/components/records/S2SRecord.tsx
src/config/network.ts
src/hooks/mappedTokens.ts
src/utils/erc20/meta.ts
src/utils/helper/balance.ts
src/utils/tx/issuing.ts
src/utils/tx/redeem.ts
yarn.lock

S2S formal bridge

---

cypress/integration/substrateDVM2Substrate.spec.ts
public/locales/en/translation.json
public/locales/zh/translation.json
src/components/bridge/DVM.tsx
src/components/bridge/Ethereum2Darwinia.tsx
src/components/bridge/SubstrateDVM2Substrate.tsx
src/components/modal/ApproveSuccess.tsx
src/hooks/tx.tsx

chore: dvm departure fee display

---

cypress/integration/substrateDVM2Substrate.spec.ts
package.json
public/locales/en/translation.json
public/locales/zh/translation.json
src/components/Configuration.tsx
src/components/bridge/DVM.tsx
src/components/bridge/Ethereum2Darwinia.tsx
src/components/bridge/Substrate2SubstrateDVM.tsx
src/components/bridge/SubstrateDVM2Substrate.tsx
src/components/finder.tsx
src/components/modal/ApproveSuccess.tsx
src/components/records/Record.tsx
src/components/records/S2SRecord.tsx
src/config/network.ts
src/hooks/mappedTokens.ts
src/hooks/tx.tsx
src/utils/erc20/meta.ts
src/utils/helper/balance.ts
src/utils/tx/issuing.ts
src/utils/tx/redeem.ts
yarn.lock

feat: support s2s formal bridge

---

src/components/records/D2ERecord.tsx
src/components/records/E2DRecord.tsx
src/components/records/Progress.tsx
src/components/records/Record.tsx
src/components/records/S2SRecord.tsx
src/config/query.ts
src/hooks/records.tsx
src/model/darwinia/dapp.ts
src/model/network.ts

fix: S2S records 

---

.github/dependbot.yml

build(deps): dependbot

---

src/components/bridge/Substrate2SubstrateDVM.tsx

fix(#244): fee estimate

---

src/components/bridge/Substrate2SubstrateDVM.tsx

chore: reserve one

---

src/components/bridge/SubstrateDVM2Substrate.tsx
src/utils/tx/issuing.ts

chore: hard code spec version

---

src/components/bridge/SubstrateDVM2Substrate.tsx

chore: bump darwinia spec version to 1180

---

cypress/integration/ethereum2Darwinia.spec.ts
src/components/records/S2SRecord.tsx
src/config/query.ts
src/hooks/records.tsx
src/model/darwinia/dapp.ts

s2s deliver hash is  incorrect

fix: deliver extrinisic link

---

src/utils/network/graph.ts

fix(#268): evm to dvm exposed in prod

---

src/model/tx.ts
src/providers/tx-provider.tsx

fix(#267): observer receive error data if tx canceled

---

src/model/tx.ts
src/providers/tx-provider.tsx
src/utils/network/graph.ts

fix: bugs may crash UI

---

src/components/form-control/AssetGroup.tsx
src/utils/tx/issuing.ts

chore: darwinia to ether max limit

---

src/components/form-control/AssetGroup.tsx
src/utils/tx/issuing.ts

Reserve a little token for fee.

fix: darwinia to ethereum max limit

---

src/components/form-control/AssetGroup.tsx
src/components/record/substrate-substrateDVM/SubstrateSubstrateDVM.tsx
src/model/darwinia/dapp.ts
src/utils/tx/common.tsx
src/utils/tx/issuing.ts

fix(#266):  tx hash link

---

.github/workflows/deploy-dev.yml
.github/workflows/notify.yml
.github/workflows/test.yml

ci: refact ci

---

cypress/integration/records.spec.ts
src/bridges/substrate-dvm/DVM2Substrate.tsx
src/bridges/substrate-dvm/Substrate2DVMRecord.tsx
src/bridges/substrate-dvm/config/query.ts
src/bridges/substrate-dvm/hooks/records.ts
src/bridges/substrate-dvm/model/record.ts
src/components/record/CrossChain.tsx
src/hooks/tx.tsx

DVM ----> main record disabled temporarily.  Need:  https://github.com/darwinia-network/darwinia-common/issues/1123

chore: dvm main record

---

.github/ISSUE_TEMPLATE/1-bug-report.yaml
.github/PULL_REQUEST_TEMPLATE.md
src/utils/connection/connection.tsx
src/utils/connection/entrance.ts

chore: remove manul connection

---

src/components/record/Progress.tsx

style: purge break the progress grids

---

public/locales/en/translation.json
public/locales/zh/translation.json
src/bridges/ethereum-darwiniaDVM/Erc20Register.tsx
src/components/Airport.tsx
src/components/CrossChain.tsx
src/components/form-control/Direction.tsx
src/components/record/Airdrop.tsx
src/components/widget/SubmitButton.tsx
src/config/bridges.ts
src/utils/bridge/bridge.ts
src/utils/connection/connection.tsx

fix: missing airdrop config

---

src/bridges/substrate-substrateDVM/hooks/records.ts

fix: s2s querying not disappear

---

src/bridges/ethereum-darwinia/config/bridge.ts
src/bridges/ethereum-darwiniaDVM/config/bridge.ts
src/bridges/substrate-dvm/config/bridge.ts
src/bridges/substrate-substrateDVM/config/bridge.ts
src/config/bridges.ts

chore: update spec versionn to 1200

---

src/bridges/DVM/DVM.tsx
src/bridges/ethereum-darwinia/config/bridge.ts
src/bridges/ethereum-darwiniaDVM/config/bridge.ts
src/bridges/ethereum-darwiniaDVM/utils/tx.ts
src/bridges/substrate-dvm/config/bridge.ts
src/bridges/substrate-substrateDVM/Substrate2SubstrateDVM.tsx
src/bridges/substrate-substrateDVM/SubstrateDVM2Substrate.tsx
src/bridges/substrate-substrateDVM/config/bridge.ts
src/bridges/substrate-substrateDVM/hooks/bridge.ts
src/bridges/substrate-substrateDVM/hooks/index.ts
src/bridges/substrate-substrateDVM/utils/index.ts
src/bridges/substrate-substrateDVM/utils/tx.ts
src/components/CrossChain.tsx
src/components/form-control/RecipientItem.tsx
src/config/bridges.ts
src/config/network/crab.ts
src/config/network/darwinia.ts
src/config/network/pangolin.ts
src/config/network/pangoro.ts
src/model/bridge/bridge.ts
src/model/bridge/cross-chain.ts
src/model/network/config.ts
src/utils/mappingToken/mappingParams.ts
src/utils/mappingToken/mappingToken.ts

feat: add bridge status check

---

src/config/network/darwinia.ts

bump darwinia spec version  to  1200

chore: bump darwinia spec version

---

package.json
plugins/antd-theme-generator.js
src/bridges/DVM/DVM.tsx
src/bridges/substrate-dvm/DVM2SubstrateRecord.tsx
src/bridges/substrate-substrateDVM/Substrate2SubstrateDVM.tsx
src/bridges/substrate-substrateDVM/SubstrateDVM2Substrate.tsx
src/bridges/substrate-substrateDVM/utils/tx.ts
src/config/network/pangolin.ts
src/config/network/pangoro.ts
yarn.lock

pangolin pangolin 28080
remove feeMarket call from RPC

chore: udpate spec version

---

src/components/widget/Footer.tsx
src/config/network/crab.ts

remove airdrop entrace
crab spec version 1210

chore: bump crab spec version to 1210

---

src/config/network/darwinia.ts

chore: bump darwina spec version

---

src/bridges/ethereum-darwinia/Ethereum2Darwinia.tsx
src/components/record/CrossChain.tsx
src/config/network/pangolin.ts
src/config/network/pangoro.ts

feat: remove deposit

---

src/config/network/crab.ts

chore: bump crab spec 1221

---

src/bridges/substrate-substrateDVM/utils/tx.ts

chore: weight

---

src/config/network/crab.ts

Bump crab spec

---

src/bridges/substrate-substrateDVM/Substrate2SubstrateDVM.tsx
src/bridges/substrate-substrateDVM/SubstrateDVM2Substrate.tsx
src/bridges/substrate-substrateDVM/utils/tx.ts

chore: rename s2s fee method

---

src/bridges/substrate-substrateDVM/Substrate2SubstrateDVM.tsx
src/bridges/substrate-substrateDVM/SubstrateDVM2Substrate.tsx
src/bridges/substrate-substrateDVM/utils/tx.ts
vercel.json

chore: updatw vercel config

---

src/bridges/substrate-substrateDVM/utils/tx.ts
src/config/network/darwinia.ts

chore: bump darwinia spec
